version: 2

before:
  hooks:
    - go mod tidy
    - go get -u
    # - go generate -x ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

nfpms:
  - id: rootisnaked
    package_name: rootisnaked
    file_name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    homepage: https://github.com/containerscrew/rootisnaked
    vendor: Containerscrew
    description: Simple root privilege escalation detection using ebpf-go
    maintainer: Containerscrew <info@containerscrew.com>
    license: GPL-3.0 license
    formats:
      - apk
      - deb
      - rpm
      - archlinux

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
